export const themeVariables = [
  '--font-body',
  '--font-mono',
  '--font-serif',
  '--color-text',
  '--color-muted',
  '--color-bg',
  '--color-accent',
  '--color-mark',
  '--color-mark-text',
  '--color-highlight',
  '--color-border',
  '--measure',
  '--measure-wide',
  '--sidenote-width',
];

export const optionalVariables = [
  '--code-foreground',
  '--code-token-keyword',
  '--code-token-comment',
  '--code-token-string',
  '--code-token-string-expression',
  '--code-token-constant',
  '--code-token-parameter',
  '--code-token-function',
  '--code-token-punctuation',
  '--code-token-link',
  '--code-token-inserted',
  '--code-token-deleted',
  '--code-token-changed',
];
